sudo: required
language: generic
services:
  - docker

before_install:
  - docker build -t geazas/docker-react -f Dockerfile.dev .

script:
  - docker run -e CI=true geazas/docker-react npm run test

deploy:
  provider: elasticbeanstalk
  region: "us-east-2"
  app: "docker-react"
  environment: "Dockerreact-env"
  bucket_name: "elasticbeanstalk-us-east-2-360061143968"
  bucker_path: "docker-react"
  on:
    branch: master
  access_key_id: $AWS_ACCESS_KEY
  secret_access_key: $AWS_SECRET_KEY